# Generated by Django 3.1 on 2020-08-23 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=50, verbose_name='street')),
                ('suite', models.CharField(max_length=10, verbose_name='suite')),
                ('city', models.CharField(blank=True, max_length=50, verbose_name='city')),
                ('zipcode', models.CharField(blank=True, max_length=10, verbose_name='zipcode')),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=30, verbose_name='name_company')),
                ('catchPhrase', models.TextField(blank=True, max_length=100, verbose_name='catch_phrase')),
                ('bs', models.TextField(blank=True, max_length=100, verbose_name='bs')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='full_name')),
                ('username', models.CharField(max_length=50, verbose_name='username')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='phone')),
                ('website', models.URLField(blank=True, max_length=100, verbose_name='website')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users',
                                              to='test_task.company')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, max_length=200, verbose_name='title')),
                ('body', models.TextField(blank=True, max_length=200, verbose_name='body')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts',
                                           to='test_task.user')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
        migrations.CreateModel(
            name='Geo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(blank=True, max_length=90, verbose_name='latitude')),
                ('longitude', models.FloatField(blank=True, max_length=180, verbose_name='longitude')),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='geo',
                                                 to='test_task.address')),
            ],
            options={
                'verbose_name': 'Geo',
                'verbose_name_plural': 'Geos',
            },
        ),
        migrations.AddField(
            model_name='address',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address',
                                    to='test_task.user'),
        ),
    ]
